### ISSUE TITLE
Agile not rendered on Nuxt production build

### ISSUE THREAD

**Issue by tillkolter** [lukaszflorczak/vue-agile#59]
I would like to use vue-agile for my mobile slider here: https://oye.kolter.it/ 

Everything is rendered correctly, when I run the dev server, but after `npm run build` and with `npm run start` I get the following exceptions and the component is not rendered (search the source code for `<agile>`).

```
[nuxt.js] Cannot load components DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.je [as appendChild] (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:19712)
    at f (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:46250)
    at i (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:45535)
    at l (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:46333)
    at x (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:49157)
    at a.__patch__ (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:49728)
    at a.t._update (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:38745)
    at a.r (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:7322)
    at Nr.get (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:35110)
    at new Nr (https://oye.kolter.it/_nuxt/vendor.bundle.51428f798a9e09b81298.js:21:34932)
(anonymous) @ nuxt.bundle.3ebab7d5bbfe02586b27.js:6
vendor.bundle.51428f798a9e09b81298.js:21 TypeError: Cannot read property '$options' of undefined
    at ct (vendor.bundle.51428f798a9e09b81298.js:21)
    at prepatch (vendor.bundle.51428f798a9e09b81298.js:21)
    at b (vendor.bundle.51428f798a9e09b81298.js:21)
    at _ (vendor.bundle.51428f798a9e09b81298.js:21)
    at b (vendor.bundle.51428f798a9e09b81298.js:21)
    at a.__patch__ (vendor.bundle.51428f798a9e09b81298.js:21)
    at a.t._update (vendor.bundle.51428f798a9e09b81298.js:21)
    at a.r (vendor.bundle.51428f798a9e09b81298.js:21)
    at Nr.get (vendor.bundle.51428f798a9e09b81298.js:21)
    at Nr.run (vendor.bundle.51428f798a9e09b81298.js:21)
i @ vendor.bundle.51428f798a9e09b81298.js:21
```

**Comment by kwdtje** [comment]
You need to use it as no ssr. Check Nuxt.js how to do it.
